version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/apps/frontend/node_modules
      - .:/usr/apps/frontend
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/apps/frontend/node_modules
      - .:/usr/apps/frontend
    command: ["npm", "run", "test"]